---
- hosts: centos
  gather_facts : False
  tasks:
  - name:  multiple items .- "{{ item }}"
    file: 
      state:  touch 
      path:  /home/{{ ansible_ssh_user }}/{{ item }}
    with_items:
      - file_no_1
      - file_no_2
      - file_no_3